server:
  port: 8081

spring:
  application:
    name: amorixa-auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ms-auth}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    initialize: true
    maxActive: 3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  auth:
    secret: 62e360a697e64542a5d27f07048ffcf2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
springdoc:
  packagesToScan: org.murilonerdx.msauth.controller
  swagger-ui:
    path: /docs-amorixa-auth.html
  api-docs:
    path: /docs-amorixa-auth
